name: Pytest & Flake8 control Push
on: push
jobs:
  qa:
    name: Check tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout on master
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: "3.x"

      - name: Upgrade pip before install tools
        run: |
          sudo apt-get update
          pip install --upgrade pip3

      - name: Install pip3 before tools
        run: |
          sudo apt-get -y install python3-pip
          pip3 --version
          pip3 install pytest-workflow
          sudo python3 -m pip3 install pytest-workflow

      - name: Install pytest and flakes
        run: |
          pip3 install -r requirements.txt
          pip3 install pytest
          pip3 install flakes

      - name: Run tests
        run: |
          pytest

      - name: Run flakes
        uses: py-actions/flake8@v2
