name: Shell commands
on:  [push]
jobs:
  run-shell-command:
    run-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: echo a string
#       run: echo "Hello world"
        run: echoo "Hello world"
#       run: echo "Hi HermannGit"
      - name: mutiline script
        run: |
          python3 -v
          touch my_file_with_worrkflow.py
          ls -l

# Ce flux de travail comporte 4 étapes en 3 jobs
# Etape 1 : Afficher les messages "Hello world" et "Hi HermannGit" successivement  dans la console
# Etape 2 : Afficher la version de Python, la version disponible par défaut dans Ubuntu
# Etape 3 : Créer un fichier pyhton nommé "my_file_with_workflow.py"
# Etape 4 : Lisez les fichiers dans le dossier actuel
